version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:3000
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/empire
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
