version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
